import type { Match } from './types'

/** The career as a tournament draw, newest first: the final in play, then back through the rounds. */
export const matches: Match[] = [
  {
    id: 'goto',
    round: 'Final',
    company: 'GoTo Group',
    location: 'Gojek · Jakarta',
    role: 'Software Engineer',
    period: 'Apr 2026 — Present',
    commentary: 'Center court, millions watching. GoFood, at scale.',
    highlights: [
      'Build and maintain high-scale GoFood backend services in Go and Clojure.',
      "Enhance merchant-facing and order management features across GoFood's ordering flow.",
      'Work on distributed production systems: features, troubleshooting and reliability.',
    ],
    stack: ['Go', 'Clojure', 'Distributed systems'],
    status: 'live',
    year: 2026,
  },
  {
    id: 'saakuru',
    round: 'Semifinal',
    company: 'Saakuru Labs',
    location: 'Singapore',
    role: 'Fullstack AI Engineer',
    period: 'May 2025 — Mar 2026',
    commentary: 'Long rallies: agents with memory, retrieval and queues.',
    highlights: [
      'Engineered agentic AI infrastructure behind an AI agents marketplace.',
      'Built a RAG pipeline and persistent memory for context-aware, personal agents.',
      'Designed an async job queue to summarize agent–user interactions at scale.',
      'Shipped end-to-end AI agent apps for clients, from backend to web UI.',
    ],
    stack: ['RAG', 'Agent memory', 'Job queues', 'TypeScript', 'Python'],
    status: 'advanced',
    year: 2025,
  },
  {
    id: 'feedloop',
    round: 'Quarterfinal',
    company: 'Feedloop AI',
    location: 'Jakarta · Contract',
    role: 'Fullstack Engineer',
    period: 'Nov 2024 — Feb 2025',
    commentary: 'Moved the heavy lifting to the baseline: async workers.',
    highlights: [
      'Built an asynchronous worker for generating opinions, raising throughput.',
      'Shipped new features such as projects, with endpoints in Express.',
      'Configured deployment of the main server and workers on Kubernetes.',
    ],
    stack: ['Express', 'Node.js', 'Workers', 'Kubernetes'],
    status: 'advanced',
    year: 2025,
  },
  {
    id: 'telkom',
    round: 'Round 2',
    company: 'Telkom Indonesia',
    location: 'Jakarta',
    role: 'Software Developer Intern',
    period: 'Aug 2024 — Nov 2024',
    commentary: 'Found the rhythm: real-time rallies, streamed end to end.',
    highlights: [
      'Created ICA, a chatbot with real-time streaming responses.',
      'Added configuration for Llama 3.1 and Azure OpenAI 4o mini.',
      'Shipped the web app end to end with Next.js, Node.js, Redis and Kubernetes.',
    ],
    stack: ['Next.js', 'Node.js', 'Redis', 'Kubernetes', 'Tailwind'],
    status: 'advanced',
    year: 2024,
  },
  {
    id: 'mostrans',
    round: 'Round 1',
    company: 'Mostrans',
    location: 'Kalbe Group · Jakarta',
    role: 'Software Engineer Intern',
    period: 'Apr 2024 — Jun 2024',
    commentary: 'A tidy opening round. Clean footwork, cleaner code.',
    highlights: [
      'Built an internal application with Deno, TypeScript, React, Recoil and Apollo GraphQL.',
      'Refactored existing code with OOP and proven refactoring techniques.',
      'Improved performance by applying design patterns and clean code.',
    ],
    stack: ['Deno', 'TypeScript', 'React', 'Recoil', 'GraphQL'],
    status: 'advanced',
    year: 2024,
  },
]
